
  rest-narration-native:
    image: quay.io/quarkus-super-heroes/rest-narration:native-latest
    container_name: rest-narration-native
    ports:
      - "8087:8087"
    environment:
      QUARKUS_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://otel-collector:4317
    restart: on-failure
    networks:
      default:
        aliases:
          - rest-narration
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'
        reservations:
          memory: 256M
          cpus: '0.5'
