apiVersion: v1
kind: Pod
metadata:
  name: myapp
  namespace: dev
  labels:
    app: firsapp
spec:
  containers:
  - name: myapp
    image: nginx
    imagePullPolicy: Never # IfNotPresent, # Always
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
