apiVersion: apps/v1
kind: Deployment
metadata:
  name: firstdeployment
spec:
  selector:
    matchLabels:
      app: firstapp
  replicas: 2
  template:
    metadata:
      labels:
        app: firstapp
    spec:
      containers:
      - name: myapp
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_USER
              name: myapp-config
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_PASSWORD
              name: mysecret
        ports:
        - containerPort: 80
