services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: exempledb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U toto -d db"]
      interval: 10s
      timeout: 30s
      retries: 1
      start_period: 10s
  redis:
    image: redis:5.0-alpine3.10
    networks:
      - vote_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]