services:
  redis:
    image: redis:5.0-alpine3.10
    networks:
      - vote_network
  db:
    image:  postgres:9.4
    volumes:
      - "data-postgres:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - result_network
  vote:
    build: ./vote
    ports:
      - "8080-8084:80"
    deploy:
      replicas: 3
    healthcheck:
      test: ["CMD-SHELL", "/usr/local/bin/healthcheck.sh"]
      interval: 10s
      timeout: 30s
      retries: 1
      start_period: 10s
    depends_on:
      - redis
    networks:
      - vote_network
    
  result:
    build: ./result
    deploy:
      replicas: 3
    ports:
      - "4000"
    depends_on:
      - db
    # environment:
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_PASSWORD=postgres
    #   - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "/usr/local/bin/healthcheck.sh"]
      interval: 10s
      timeout: 30s
      retries: 1
      start_period: 10s
    networks:
      - result_network
  worker:
    build: ./worker
    depends_on:
      - db
      - redis
    networks:
      - vote_network
      - result_network
    healthcheck:
      test: ["CMD-SHELL", "/usr/local/bin/healthcheck.sh"]
      interval: 10s
      timeout: 30s
      retries: 1
      start_period: 10s

volumes:
  data-postgres:

networks:
  vote_network:
  result_network:
  